### ISSUE TITLE
TypeError: _a.defineFunctionEventProperties is not a function

### ISSUE THREAD

**Issue by mrcarromesa** [SamWSoftware/serverless-auto-swagger#48]
I got the following error when I ran the command:

Command:

```shell
serverless deploy --stage dev
```

Result:

```shell
serverless deploy --stage dev     
 
  Type Error ---------------------------------------------
 
  TypeError: _a.defineFunctionEventProperties is not a function
      at ServerlessAutoSwagger.registerOptions (MY_PROJECT_PAHT/node_modules/serverless-auto-swagger/dist/ServerlessAutoSwagger.js:34:96)
      at new ServerlessAutoSwagger (MY_PROJECT_PAHT/node_modules/serverless-auto-swagger/dist/ServerlessAutoSwagger.js:402:14)
      at PluginManager.addPlugin (/MY_USER_FOLDER/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:84:28)
      at /MY_USER_FOLDER/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:121:31
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (/MY_USER_FOLDER/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:121:8)
      at /MY_USER_FOLDER/.config/yarn/global/node_modules/serverless/lib/Serverless.js:101:35
      at tryCatcher (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._settlePromise (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:617:21)
      at Promise._settlePromise0 (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:673:18)
      at PromiseArray._resolve (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise_array.js:127:19)
      at PromiseArray._promiseFulfilled (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise_array.js:145:14)
      at Promise._settlePromise (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._settlePromise0 (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:673:18)
      at PropertiesPromiseArray.PromiseArray._resolve (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise_array.js:127:19)
      at PropertiesPromiseArray._promiseFulfilled (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/props.js:78:14)
      at Promise._settlePromise (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._settlePromise0 (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/MY_USER_FOLDER/.config/yarn/global/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:464:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.18.1
     Framework Version:         1.78.1
     Plugin Version:            3.7.0
     SDK Version:               2.3.1
     Components Version:        2.34.1
```

In my webpack.config.js I already added this:

```js
extensions: ['.mjs', '.json', '.ts', '.js'],
```

Only when I run locally with `serverless offline start --stage local`

It works fine, but when I try to deploy it returns the above error.

My serverless and auto-swagger versions:

```
"serverless": "^3.2.1",
"serverless-auto-swagger": "^2.1.0",
```

**Comment by bfaulk96** [comment]
What is the order of your plugins in your serverless file?

**Comment by mrcarromesa** [comment]
> What is the order of your plugins in your serverless file?
> Also, what is your current serverless framework version in your serverless file?

I updated serverless to the latest version and used npm instead of yarn and it worked! Without further ado, I'm closing the issue! Thanks
