### ISSUE TITLE
 serverless-auto-swagger -  TypeError 

### ISSUE THREAD

**Issue by sunilnalumachu** [SamWSoftware/serverless-auto-swagger#61]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*:  2.52.1

*Implementations:*  Node serverless framework

*Framework version:*  serverless version  2.52.1, node: 14.17

*Frontend service:* REST API

*Deployment method:* Serverless Framework

## Scenario
*Describe what you are trying to accomplish*

I am trying to use serverless-auto-swagger plugin to generate swagger docs for my rest apis. I am using node with serverless project with typescript and aws resources.

## Expected behavior
*Describe how you would expect the application to behave*
I am expecting to deploy my service with swaggers plugin to generate swagger docs for my rest apis.

## Actual behavior
*Describe what you are seeing instead*
when i try to deploy my service to my stage, like sls deploy --stage=test, I am seeing an error inside the swagger plugin states Cannot destructure property 'log' of 'undefined' as it is undefined.
      at new ServerlessAutoSwagger (app/node_modules/serverless-auto-swagger/dist/ServerlessAutoSwagger.js:21:40)

and i am unable to deploy because of this error.

I followed all the instructions in doc like added package version of "serverless-auto-swagger": "^2.4.0", and added serverless-auto-swagger plugin in serverless plugins and added in webpack extensions.

## Steps to reproduce
*Provide code samples we can use to reproduce the issue as part of our integration tests. If there is a public repository for the misbehaving application link to it here*

## Full log output
Serverless: Running "serverless" installed locally (in service node_modules)

*Paste the full log output from the Lambda function's CloudWatch logs*
 TypeError: Cannot destructure property 'log' of 'undefined' as it is undefined.
      at new ServerlessAutoSwagger (app/node_modules/serverless-auto-swagger/dist/ServerlessAutoSwagger.js:21:40)
      at PluginManager.addPlugin (app/node_modules/serverless/lib/classes/PluginManager.js:112:28)
      at app/node_modules/serverless/lib/classes/PluginManager.js:158:33
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (app/node_modules/serverless/lib/classes/PluginManager.js:158:8)
      at Serverless.init (app/node_modules/serverless/lib/Serverless.js:209:30)
      at async Serverless.eventuallyFallbackToLocal (.nvm/versions/node/v14.17.0/lib/node_modules/serverless/lib/Serverless.js:270:5)
      at async Serverless.init (.nvm/versions/node/v14.17.0/lib/node_modules/serverless/lib/Serverless.js:197:5)
      at async .nvm/versions/node/v14.17.0/lib/node_modules/serverless/scripts/serverless.js:499:7

**Comment by bfaulk96** [comment]
This was caused because I accidentally implemented a Serverless 3.0.0 breaking change. I am in the process of fixing.

**Comment by sunilnalumachu** [comment]
Thank you so much for fixing and quick resolve to the issue .

**Comment by bfaulk96** [comment]
No problem, sorry that I caused this in the first place!

**Comment by bfaulk96** [comment]
Also, thank you for the very in-depth explanation of your issue 😄 
Always makes helping easier
